#!/bin/bash

echo "Total number of folders (including all nested ones) = $TOTAL_FOLDERS"
echo "TOP 5 folders of maximum size arranged in descending order (path and size):"  
echo "$TOP_FOLDERS"
echo "etc up to 5"
echo "Total number of files = $NUMBER_FILES"
echo "Number of:"  
echo "Configuration files (with the .conf extension) = $NUMBER_CONF"
echo "Text files = $NUMBER_TXT" 
echo "Executable files = $NUMBER_EXE"
echo "Log files (with the extension .log) = $NUMBER_LOG"
echo "Archive files = $NUMBER_ARCH" 
echo "Symbolic links = $LINKS"  
echo "TOP 10 files of maximum size arranged in descending order (path, size and type):" 
echo "$TOP_LARGEST_FILES"
echo "etc up to 10" 
echo "TOP 10 executable files of the maximum size arranged in descending order (path, size and MD5 hash of file):"  
echo "$TOP_LARGEST_EXE"
echo "etc up to 10" 
