#!/bin/bash
#
chmod +x ../02/get_info.sh
source ../02/get_info.sh

printf "\e[${COLUMN1_BACKGROUND};${COLUMN1_FONT_COLOR}mHOSTNAME\e[${RESET}m = \e[${COLUMN2_BACKGROUND};${COLUMN2_FONT_COLOR}m$HOSTNAME\e[${RESET}m\n"
printf "\e[${COLUMN1_BACKGROUND};${COLUMN1_FONT_COLOR}mTIMEZONE\e[${RESET}m = \e[${COLUMN2_BACKGROUND};${COLUMN2_FONT_COLOR}m$TIMEZONE\e[${RESET}m\n"
printf "\e[${COLUMN1_BACKGROUND};${COLUMN1_FONT_COLOR}mUSER\e[${RESET}m = \e[${COLUMN2_BACKGROUND};${COLUMN2_FONT_COLOR}m$USER\e[${RESET}m\n"
printf "\e[${COLUMN1_BACKGROUND};${COLUMN1_FONT_COLOR}mOS\e[${RESET}m  = \e[${COLUMN2_BACKGROUND};${COLUMN2_FONT_COLOR}m$OS\e[${RESET}m\n"
printf "\e[${COLUMN1_BACKGROUND};${COLUMN1_FONT_COLOR}mDATE\e[${RESET}m  = \e[${COLUMN2_BACKGROUND};${COLUMN2_FONT_COLOR}m$DATE\e[${RESET}m\n"
printf "\e[${COLUMN1_BACKGROUND};${COLUMN1_FONT_COLOR}mUPTIME\e[${RESET}m  = \e[${COLUMN2_BACKGROUND};${COLUMN2_FONT_COLOR}m$UPTIME\e[${RESET}m\n"
printf "\e[${COLUMN1_BACKGROUND};${COLUMN1_FONT_COLOR}mUPTIME_SEC\e[${RESET}m  = \e[${COLUMN2_BACKGROUND};${COLUMN2_FONT_COLOR}m$UPTIME_SEC\e[${RESET}m\n"
printf "\e[${COLUMN1_BACKGROUND};${COLUMN1_FONT_COLOR}mGATEWAY\e[${RESET}m  = \e[${COLUMN2_BACKGROUND};${COLUMN2_FONT_COLOR}m$GATEWAY\e[${RESET}m\n"
printf "\e[${COLUMN1_BACKGROUND};${COLUMN1_FONT_COLOR}mRAM_TOTAL\e[${RESET}m  = \e[${COLUMN2_BACKGROUND};${COLUMN2_FONT_COLOR}m$RAM_TOTAL\e[${RESET}m\n"
printf "\e[${COLUMN1_BACKGROUND};${COLUMN1_FONT_COLOR}mRAM_USED\e[${RESET}m  = \e[${COLUMN2_BACKGROUND};${COLUMN2_FONT_COLOR}m$RAM_USED\e[${RESET}m\n"
printf "\e[${COLUMN1_BACKGROUND};${COLUMN1_FONT_COLOR}mRAM_FREE\e[${RESET}m  = \e[${COLUMN2_BACKGROUND};${COLUMN2_FONT_COLOR}m$RAM_FREE\e[${RESET}m\n"
printf "\e[${COLUMN1_BACKGROUND};${COLUMN1_FONT_COLOR}mSPACE_ROOT\e[${RESET}m  = \e[${COLUMN2_BACKGROUND};${COLUMN2_FONT_COLOR}m$SPACE_ROOT\e[${RESET}m\n"
printf "\e[${COLUMN1_BACKGROUND};${COLUMN1_FONT_COLOR}mSPACE_ROOT_USED\e[${RESET}m  = \e[${COLUMN2_BACKGROUND};${COLUMN2_FONT_COLOR}m$SPACE_ROOT_USED\e[${RESET}m\n"
printf "\e[${COLUMN1_BACKGROUND};${COLUMN1_FONT_COLOR}mSPACE_ROOT_FREE\e[${RESET}m  = \e[${COLUMN2_BACKGROUND};${COLUMN2_FONT_COLOR}m$SPACE_ROOT_FREE\e[${RESET}m\n"

